### PR TITLE
Remove Gaia 1.3 and 1.4, now obsolete

### PR DESCRIPTION
**Pull request by pascalchevrel**

### CODE REVIEW

**Comment by flodolo** [comment]
Two nits:
* Update the display_order for the following repositories (ignoring l20n).
* Remove the .txt files for 1.3 and 1.4 from [this folder](https://github.com/pascalchevrel/mozilla-l10n-query/tree/master/sources)

**Comment by pascalchevrel** [comment]
updated

**Comment by flodolo** [comment]
Looks good, thanks.

**Comment by flodolo** [comment]
Fixed in the correct repository too (I gave you my fork URL by mistake)
https://github.com/mozilla-l10n/mozilla-l10n-query/pull/25

**Pull request merged**
